from pathlib import Path

ROOT_DIR = Path(__file__).parent

ACTION_MOVE_FORWARD = 0
ACTION_TURN_LEFT = 1
ACTION_TURN_RIGHT = 2
ACTION_GRAB = 3
ACTION_CLIMB = 4
ACTION_SHOOT = 5

GRID_SIZE = 4

SENSATION_MAPS_SIZE = ((GRID_SIZE*2 - 1) ** 2) * 2 + ((GRID_SIZE*2 + 1) ** 2)
SENSATION_STATE_DIM = 10 + SENSATION_MAPS_SIZE
# STATE_DIM = 10
STATE_DIM = SENSATION_STATE_DIM